describe('Teste de filtrar por data', () => {
    it('Filtrar por data com espaço no período', () => {
        cy.visit('/');
        cy.get('#entrar').click();
        cy.get('.forget').click();
        cy.get('#username').type("beta");
        cy.get('#name').type('beta');
        cy.get(':nth-child(5) > #email').type('beta@123.com');
        cy.get('#password').type('123');
        cy.wait(1000);
        cy.get('.btn_login').click();
        cy.get('[aria-current="page"]').click();
        cy.get('#nome').type('Casa campo');
        cy.get('#descricao').type('Casa no campo com um vasto jardim calmo e bela vista para as colinas.');
        cy.get('#preco_por_noite').type('750');
        cy.get('#endereco').type('Rua das colinas, 100');
        cy.get('#cidade').type('Bonito');
        cy.get('#estado').type('Pernambuco');
        cy.get('#pais').type('Brasil');
        cy.get('#numero_de_quartos').type('4');
        cy.get('#numero_de_banheiros').type('5');
        cy.get('#numero_de_hospedes').type('10');
        cy.get('#foto_principal').attachFile('imgs/chale_Floresta.jpg');
        cy.wait(1000);
        cy.get('.container > form > .btn').click();
        cy.get('#sair').click();
        cy.get('#entrar').click();
        cy.get('.forget').click();
        cy.get('#username').type("beto");
        cy.get('#name').type('beto');
        cy.get(':nth-child(5) > #email').type('beto@123.com');
        cy.get('#password').type('123');
        cy.wait(1000);
        cy.get('.btn_login').click();
        cy.get('#checkin_date').type('2025-07-20');
        cy.get('#checkout_date').type('2025-07-23');
        cy.wait(1000);
        cy.get(':nth-child(2) > .search-container > .input-group > .input-group-append > .btn').click();
        cy.get('.col').should('exist');
    });
});
