# Generated by Django 5.0.4 on 2024-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario_nome', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco_por_noite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('numero_de_quartos', models.PositiveIntegerField(default=1)),
                ('numero_de_banheiros', models.PositiveIntegerField(default=1)),
                ('numero_de_hospedes', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espaco_proprietario_nome', models.CharField(max_length=100)),
                ('espaco_nome', models.CharField(default='Nome do Espaço Padrão', max_length=100)),
                ('hospede_nome', models.CharField(max_length=100)),
                ('data_check_in', models.DateField()),
                ('data_check_out', models.DateField()),
                ('numero_de_hospedes', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
