# Generated by Django 5.0.4 on 2024-04-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('sinal_reserva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.espaco')),
            ],
        ),
    ]
