# Generated by Django 5.0.3 on 2024-04-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='sinal_reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Detalhes',
        ),
    ]
