# Generated by Django 5.0.3 on 2024-04-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_espaco_sinal_reserva_delete_detalhes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='espaco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apps.espaco'),
            preserve_default=False,
        ),
    ]
