# Generated by Django 5.0.3 on 2024-05-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_reserva_espaco'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
