# Generated by Django 5.0.3 on 2024-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_reserva_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaco',
            name='sinal_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='parcela',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_parcelas',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
