# Generated by Django 5.0.3 on 2024-05-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_reserva_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='parcela',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
