# Generated by Django 5.0.4 on 2024-05-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_reserva_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comentario_avaliacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
