# Generated by Django 5.0.4 on 2024-05-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_reserva_valor_parcelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='carrossel_imagens/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
