name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Atualizado para v3 que usa Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # Atualizado para v4 que usa Node.js 20
      with:
        python-version: '3.10'  # Atualizado para Python 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Projeto\\requirements.txt
      shell: cmd

    - name: Run Django migrations
      run: |
        cd Projeto
        python manage.py migrate
      shell: cmd

    - name: Run Django tests
      run: |
        cd Projeto
        python manage.py test
      shell: cmd

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Atualizado para v3 que usa Node.js 20
      with:
        node-version: '20'

    - name: Install Cypress
      run: |
        cd Projeto
        npm install
        npx cypress install
      shell: cmd

    - name: Run Cypress tests
      run: |
        cd Projeto
        npx cypress run --config integrationFolder=Projeto/cypress/e2e
      shell: cmd
